name: HACS

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "41 4 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  hacs:
    name: HACS validation
    runs-on: ubuntu-latest

    steps:
      - name: Run HACS validation
        uses: hacs/action@main
        with:
          category: integration
          comment: false
